### ISSUE TITLE
OS Download

### ISSUE THREAD

**Issue by guoyunhe** [openSUSE/www-o-o#2]
I suggest to move OS download pages from software.opensuse.org to www.opensuse.org, because the OS download page is one of the most important thing that visitors look for in the site.

**Comment by hellcp** [comment]
It would be very hard to explain 4 different OSes (Tumbleweed, Leap, Kubic and MicroOS) with 4 different purposes each (Desktop, Server, Cloud and Embedded) on a page that is supposed to focus on much more than just OSes. Instead I think we should link the 4 purposes to get-o-o, since this is most likely what the user came to see and explain what benefits distros have for the purpose.

This is how Ubuntu and Fedora are linking to their download pages too, so it would seem to make the most sense for us, who have more or less the same number of distros as they do.

**Comment by vinzv** [comment]
Well, no. Both Fedora and Ubuntu have downloads right in sight on their landing page:

1) Fedora has their main distributions sitting right on getfedora.org (where fedoraproject.org) is pointing to.

2) Ubuntu has a button right in the middle leading to an overview of all available distributions
![image](https://user-images.githubusercontent.com/74432/80418756-2c8d6980-88d8-11ea-81f6-9999f7d6dc54.png)

I'd propose the following:
1. Let's categorize or even prioritize our distributions
2. Let's make splits right on www-o-o
3. Give very brief introductions linking to subpages

Here's a quick scheme to illustrate this whole thing in one (!) landing page:
![image](https://user-images.githubusercontent.com/74432/80419781-09fc5000-88da-11ea-9876-bc6f3605a997.png)

**Comment by hellcp** [comment]
> Well, no. Both Fedora and Ubuntu have downloads right in sight on their landing page:
> 
>     1. Fedora has their main distributions sitting right on getfedora.org (where fedoraproject.org) is pointing to.

Which are created for specific usecases, Workstation for workstation/desktop, Server for server/homeserver, CoreOS for containerized workflows etc

>     2. Ubuntu has a button right in the middle leading to an overview of all available distributions
>        ![image](https://user-images.githubusercontent.com/74432/80418756-2c8d6980-88d8-11ea-81f6-9999f7d6dc54.png)

Yup, looks about like something like I would wanna do

> Here's a quick scheme to illustrate this whole thing in one (!) landing page:
> ![image](https://user-images.githubusercontent.com/74432/80419781-09fc5000-88da-11ea-9876-bc6f3605a997.png)

Leap is a workstation/server distro and Tumbleweed is a desktop/homeserver distro, and I would argue we can't just kick them out to be all desktop, because that certainly isn't true. Also Kubic isn't for containers, but for running containers, MicroOS and (Leap and Tumbleweed) JeOS are for containers. I hope this makes it clear we can't just place explanations for all of that on the main page of the project and should instead relegate it as material for get.opensuse.org, because this is way too confusing for two lines as we currently explain Tumbleweed and Leap on the main project site ;)

**Comment by vinzv** [comment]
> I hope this makes it clear we can't just place explanations for all of that on the main page of the project and should instead relegate it as material for get.opensuse.org, because this is way too confusing for two lines as we currently explain Tumbleweed and Leap on the main project site ;)

Sure, I am aware of the overlap. But to get a starting point we will need to make compromises. My idea was to mostly get rid of the distribution's names and replace it with "openSUSE for xxx" as a purpose driven starting point.

As someone completely new to openSUSE I expect the landing page to guide me towards what I wanna do with it and not to slap some names at my table.

**Comment by vinzv** [comment]
I re-thought my initial scheme and built a new one which should mostly be self-explanatory. The whole stuff is just a scheme and following the idea of how content is to be presented.

![schematics2](https://user-images.githubusercontent.com/74432/81005561-70d7b700-8e4e-11ea-8859-3231d9748ab4.png)
Any comments and critics?

**Comment by guoyunhe** [comment]
Other good to have:

0. top reasons to choose openSUSE over others.
1. a brief list of distros: Leap, Leap Beta, Tumbleweed.
2. pc suppliers with openSUSE pre-installed.
3. cloud hosting services that provide openSUSE instance.

**Comment by hellcp** [comment]
I think we should do a distro-specific block before the introduction, and have a few buttons for `Downloads for Server` and `Downloads for Desktop` or something like that. I don't think the project should take this much focus away from distros. This should probably somewhat tie into what @guoyunhe is suggesting, but this again should probably be mentioned in the tracker for https://github.com/openSUSE/get-o-o since that's where the distro info is gonna be

We can probably yeet the footer, since it's not something we do anymore, and just have the megamenu.

As for the tools, we should probably showcase the tools that go into the categories better, with some logos and links to project sites like:

```
___________________
|  Category Logo  |  Category Logo     Category Logo
|  Category Name  |  Category Name     Category Name
|                 |_____________________________________________
|
|    Category Summary
|    And a few lines of the summary at that, mentioning various
|    tools that go into it
|
|    Tool logo     Tool logo
|    Tool name     Tool name
________________________________________________________________
```
maybe even going as far as adding per-category image

**Comment by vinzv** [comment]
> I think we should do a distro-specific block before the introduction, and have a few buttons for `Downloads for Server` and `Downloads for Desktop` or something like that. I don't think the project should take this much focus away from distros. This should probably somewhat tie into what @guoyunhe is suggesting, but this again should probably be mentioned in the tracker for https://github.com/openSUSE/get-o-o since that's where the distro info is gonna be

That brings up the earlier question of how to separate distros which is why I kept the introduction very general. I imagine a visitor gets on www-o-o, skims the introduction and than wants go "get openSUSE" or at least see more details. 
The big download button leads to get-o-o where (with the same look like on www-o-o) all distributions are explained. Following your proposal for the tools section we could build it like that:

```
___________________
|  Distro Logo      |  Distro Logo     Distro Logo
|  Distro Category  |  Distro Category     Distro Category
|                   |_____________________________________________
|
|    Category Summary
|    And a few lines of the summary at that, mentioning various
|    distros that go into it
|
|    Distro logo     Distro logo
|    Distro name     Distro name
________________________________________________________________
```

> 
> We can probably yeet the footer, since it's not something we do anymore, and just have the megamenu.

I'm okay with that but depending on how long the whole page gets the megamenu maybe should be sticky. (That's something to consider for planet-o-o as well, btw. See: openSUSE/jekyll-theme#11)

> 
> As for the tools, we should probably showcase the tools that go into the categories better, with some logos and links to project sites like:
> […]
> maybe even going as far as adding per-category image

+1

**Comment by hellcp** [comment]
+1 for sticky header

**Comment by vinzv** [comment]
So, how do we proceed from here?

**Comment by hellcp** [comment]
This is solved by get.opensuse.org now
